import { Router } from "express";
import { getDashboard, getRevenueChart, getAttendanceSummary, getEnquiryConversion } from "../controllers/analytics.controller.js";
import { protect, allRoles } from "../middleware/auth.middleware.js";
const router = Router();
router.use(protect);
router.get("/dashboard",          allRoles, getDashboard);
router.get("/revenue",            allRoles, getRevenueChart);
router.get("/attendance-summary", allRoles, getAttendanceSummary);
router.get("/enquiry-conversion", allRoles, getEnquiryConversion);
export default router;
