import { Router } from "express";
import { getEnquiries, createEnquiry, getEnquiry, updateEnquiry, addFollowUp, convertToStudent, getEnquiryStats } from "../controllers/enquiry.controller.js";
import { protect, allRoles, adminAndAbove } from "../middleware/auth.middleware.js";
import { validate } from "../middleware/validate.middleware.js";
import { createEnquirySchema, updateEnquirySchema, addFollowUpSchema, convertEnquirySchema } from "../validators/schemas.js";
const router = Router();
router.use(protect);
router.get("/",       allRoles, getEnquiries);
router.post("/",      allRoles, validate(createEnquirySchema), createEnquiry);
router.get("/stats",  allRoles, getEnquiryStats);
router.get("/:id",            allRoles, getEnquiry);
router.put("/:id",            allRoles, validate(updateEnquirySchema), updateEnquiry);
router.post("/:id/followup",  allRoles, validate(addFollowUpSchema), addFollowUp);
router.put("/:id/convert",    adminAndAbove, validate(convertEnquirySchema), convertToStudent);
export default router;
