import { Router } from "express";
import { getSettings, updateSettings, updateBranding } from "../controllers/settings.controller.js";
import { protect, ownerOnly } from "../middleware/auth.middleware.js";
import { validate } from "../middleware/validate.middleware.js";
import { updateSettingsSchema, updateBrandingSchema } from "../validators/schemas.js";
const router = Router();
router.use(protect);
router.get("/",          ownerOnly, getSettings);
router.put("/",          ownerOnly, validate(updateSettingsSchema), updateSettings);
router.put("/branding",  ownerOnly, validate(updateBrandingSchema), updateBranding);
export default router;
