import { Router } from "express";
import { getStudents, searchStudents, createStudent, getStudent, updateStudent, deleteStudent, getStudentAttendance, getStudentFees, getStudentResults, getStudentHistory, transferStudent, exportStudentsCSV } from "../controllers/student.controller.js";
import { protect, adminAndAbove, teacherAndAbove, allRoles } from "../middleware/auth.middleware.js";
import { validate } from "../middleware/validate.middleware.js";
import { createStudentSchema, updateStudentSchema, transferStudentSchema } from "../validators/schemas.js";
const router = Router();
router.use(protect);
router.get("/search",       searchStudents);
router.get("/export/csv",   allRoles, exportStudentsCSV);
router.get("/",       allRoles, getStudents);
router.post("/",      adminAndAbove, validate(createStudentSchema), createStudent);
router.get("/:id",            allRoles, getStudent);
router.put("/:id",            adminAndAbove, validate(updateStudentSchema), updateStudent);
router.delete("/:id",         adminAndAbove, deleteStudent);
router.get("/:id/history",    allRoles, getStudentHistory);
router.get("/:id/attendance", allRoles, getStudentAttendance);
router.get("/:id/fees",       allRoles, getStudentFees);
router.get("/:id/results",    allRoles, getStudentResults);
router.put("/:id/transfer",   adminAndAbove, validate(transferStudentSchema), transferStudent);
export default router;
