import { Router } from "express";
import { getTests, createTest, getTest, updateTest, enterResults, getTestResults } from "../controllers/test.controller.js";
import { protect, teacherAndAbove, allRoles } from "../middleware/auth.middleware.js";
import { validate } from "../middleware/validate.middleware.js";
import { createTestSchema, updateTestSchema, enterResultsSchema } from "../validators/schemas.js";
const router = Router();
router.use(protect);
router.get("/",    allRoles, getTests);
router.post("/",   teacherAndAbove, validate(createTestSchema), createTest);
router.get("/:id",           allRoles, getTest);
router.put("/:id",           teacherAndAbove, validate(updateTestSchema), updateTest);
router.post("/:id/results",  teacherAndAbove, validate(enterResultsSchema), enterResults);
router.get("/:id/results",   allRoles, getTestResults);
export default router;
